title: Arsh Rai
baseURL: /
params:
  description: Arsh Rai's Portfolio
  layout_style: overflow
  palette: blue
  header:
    type: header
    title: Arsh Rai
    tagline: Content Designer | UX Writer
    profile_img: /images/website-image-profile-photo.png
    profile_img_alt: Author avatar
    background: dark
    has_nav: true
    nav_links:
      - type: action
        label: Home
        url: /
        style: link
      - type: action
        label: Blog
        url: /blog/
        style: link
      - type: action
        label: Music
        url: /music/
        style: link
      - type: action
        label: About
        url: /about/
        style: link
      - type: action
        label: Contact
        url: /contact/
        style: link
    has_social: true
    social_links:
      - type: action
        label: LinkedIn
        url: 'https://www.linkedin.com/in/arshabhirai/'
        style: icon
        icon_class: fa-linkedin
        new_window: true
      - type: action
        label: GitHub
        url: 'https://github.com/ArshRai17'
        style: icon
        icon_class: fa-github
        new_window: true
      - type: action
        label: Medium
        url: 'https://arshrai-ca.medium.com/'
        style: icon
        icon_class: fa-medium
        new_window: true
      - label: youtube
        url: 'https://www.youtube.com/channel/UCswslInf1qC9DJIcYkWSyRg/featured'
        style: icon
        icon_class: fa-youtube
        new_window: true
        no_follow: false
        type: action
      - type: action
        label: Instagram
        url: 'https://www.instagram.com/rcb___rai/'
        style: icon
        icon_class: fa-instagram
        new_window: true
  footer:
    type: footer
    content: >-
      &copy; arshabhirai.com. All rights reserved. Site created with <a
      href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a> &#10084;  Kick-ass hosting
      provided by <a href="https://www.netlify.com/"  target="_blank"
      rel="noopener">Netlify </a>&#10084 
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
