title: Stackbit Fresh Theme
baseURL: /
params:
  description: Personal blogging theme for Stackbit
  layout_style: overflow
  palette: blue
  header:
    type: header
    title: Arsh Rai
    tagline: Content Designer
    profile_img: /images/20180722_010953.jpg
    profile_img_alt: Author avatar
    background: dark
    has_nav: true
    nav_links:
      - type: action
        label: Home
        url: /
        style: link
      - type: action
        label: Blog
        url: /blog/
        style: link
      - type: action
        label: Music
        url: /music/
        style: link
      - type: action
        label: About
        url: /about/
        style: link
      - type: action
        label: Contact
        url: /contact/
        style: link
    has_social: true
    social_links:
      - type: action
        label: LinkedIn
        url: 'https://www.linkedin.com/in/arshabhirai/'
        style: icon
        icon_class: fa-linkedin
        new_window: true
      - type: action
        label: GitHub
        url: 'https://github.com/ArshRai17'
        style: icon
        icon_class: fa-github
        new_window: true
      - type: action
        label: Instagram
        url: 'https://www.instagram.com/rcb_rai/'
        style: icon
        icon_class: fa-instagram
        new_window: true
      - type: action
        label: Twitter
        url: 'https://twitter.com/arshrai_?lang=en'
        style: icon
        icon_class: fa-twitter
        new_window: true
      - label: youtube
        url: 'https://www.youtube.com/channel/UCswslInf1qC9DJIcYkWSyRg/featured'
        style: icon
        icon_class: fa-youtube
        new_window: false
        no_follow: false
        type: action
      - type: action
        label: DEV
        url: 'https://dev.to/'
        style: icon
        icon_class: fa-dev
        new_window: true
  footer:
    type: footer
    content: >-
      &copy; arshabhirai. All rights reserved. This Jamstack site was created
      with <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=fresh&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
